#!/bin/bash
set -e

# Required env vars
: "${VITE_COMMIT_SHA?Need to set VITE_COMMIT_SHA}"
: "${VITE_AUTH_SERVER_URL?Need to set VITE_AUTH_SERVER_URL}"
: "${VITE_JIRA_CLIENT_ID?Need to set VITE_JIRA_CLIENT_ID}"
: "${VITE_JIRA_SCOPE?Need to set VITE_JIRA_SCOPE}"
: "${VITE_JIRA_CALLBACK_URL?Need to set VITE_JIRA_CALLBACK_URL}"
: "${VITE_JIRA_API_URL?Need to set VITE_JIRA_API_URL}"
: "${VITE_STATUS_REPORTS_ENV?Need to set VITE_STATUS_REPORTS_ENV}"
: "${AWS_SECRET_ACCESS_KEY?Need to set AWS_SECRET_ACCESS_KEY}"
: "${AWS_ACCESS_KEY_ID?Need to set AWS_ACCESS_KEY_ID}"
: "${JIRA_CLIENT_SECRET?Need to set JIRA_CLIENT_SECRET}"
: "${FIGMA_CLIENT_ID?Need to set FIGMA_CLIENT_ID}"
: "${FIGMA_OAUTH_SCOPES?Need to set FIGMA_OAUTH_SCOPES}"
: "${FIGMA_CLIENT_SECRET?Need to set FIGMA_CLIENT_SECRET}"
: "${PORT?Need to set PORT}"

cat <<EOF > .env
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

VITE_COMMIT_SHA=$VITE_COMMIT_SHA
VITE_AUTH_SERVER_URL=$VITE_AUTH_SERVER_URL
VITE_JIRA_CLIENT_ID=$VITE_JIRA_CLIENT_ID
VITE_JIRA_SCOPE=$VITE_JIRA_SCOPE
VITE_JIRA_CALLBACK_URL=$VITE_JIRA_CALLBACK_URL
VITE_JIRA_API_URL=$VITE_JIRA_API_URL
VITE_STATUS_REPORTS_ENV=$VITE_STATUS_REPORTS_ENV

JIRA_CLIENT_SECRET=$JIRA_CLIENT_SECRET

FIGMA_CLIENT_ID=$FIGMA_CLIENT_ID
FIGMA_OAUTH_SCOPES=$FIGMA_OAUTH_SCOPES
FIGMA_CLIENT_SECRET=$FIGMA_CLIENT_SECRET

PORT=$PORT
EOF

# Need repo_env for ec2-deploy
cp .env repo_env

echo "PORT: $PORT"