name: Jira-destroy
on:
  workflow_dispatch:
    inputs:
      aws_ec2-resource_identifier:
jobs:
  destroy-server:
    runs-on: ubuntu-latest
    steps:
      - id: destroy
        name: Destroy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS}}
          aws_default_region: us-east-1
          aws_resource_identifier: ${{ github.event.inputs.aws_ec2-resource_identifier }}

          tf_stack_destroy: true
